name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: make install
      
    - name: Run lint
      run: make lint
      
    - name: Run test
      run: make test
